import csv

leads = [
    # --- TANZANIA & ZANZIBAR ---
    {
        'Business_Name': 'Karibu Camps & Lodges',
        'Country_Region': 'Tanzania (Serengeti / Ngorongoro)',
        'Category': 'Luxury Safari Camp & Lodge Collection',
        'Contact_Person_Or_Title': 'General Manager / Reservations Lead',
        'Primary_Outreach_Email': 'jambo@karibucamps.com',
        'Secondary_Email': 'info@karibucamps.com',
        'WhatsApp_Number': '+255758860002',
        'Phone_Number': '+255789193333',
        'Website_URL': 'https://karibucamps.com',
        'Instagram_Page': 'https://instagram.com/karibucamps',
        'Facebook_Page': 'https://facebook.com/karibucamps',
        'AI_Visibility_Gap_Signal': 'ChatGPT cites Booking.com aggregators for Serengeti luxury camps; direct Karibu domain missing from top 3 AI answers.',
        'Estimated_Monthly_Bleed_USD': '4200',
        'Tailored_Pitch_Hook': 'Karibu Camps has world-class Serengeti properties, but travelers using ChatGPT and Perplexity are being routed to OTAs taking 18% per tent.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled (Day 3)',
        'Notes': 'High ticket luxury camp. Great candidate for GEO Schema + AI allowlist.'
    },
    {
        'Business_Name': 'Into Wild Africa Luxury Safari',
        'Country_Region': 'Tanzania (Arusha / Serengeti)',
        'Category': 'Safari Lodge & Mobile Tented Camps',
        'Contact_Person_Or_Title': 'Managing Director / Reservations',
        'Primary_Outreach_Email': 'info@intowildafrica.com',
        'Secondary_Email': 'reservations@intowildafrica.com',
        'WhatsApp_Number': '+255754665827',
        'Phone_Number': '+255754665827',
        'Website_URL': 'https://intowildafrica.com',
        'Instagram_Page': 'https://instagram.com/intowildafrica',
        'Facebook_Page': 'https://facebook.com/intowildafrica',
        'AI_Visibility_Gap_Signal': 'Missing JSON-LD Lodging Schema; Perplexity cites international aggregators when asked for authentic Tanzania bush camps.',
        'Estimated_Monthly_Bleed_USD': '3600',
        'Tailored_Pitch_Hook': 'International safari inquiries in Arusha are bypassing your direct site because AI search engines lack structured entity markup for Into Wild Africa.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Arusha hub operator. Excellent WhatsApp responsiveness.'
    },
    {
        'Business_Name': 'Tarangire Safari Lodge',
        'Country_Region': 'Tanzania (Tarangire National Park)',
        'Category': 'Classic Safari Lodge & Tented Camp',
        'Contact_Person_Or_Title': 'General Manager / Bookings Team',
        'Primary_Outreach_Email': 'bookings@tarangiresafarilodge.com',
        'Secondary_Email': 'info@tarangiresafarilodge.com',
        'WhatsApp_Number': '+255658820030',
        'Phone_Number': '+255658820030',
        'Website_URL': 'https://tarangiresafarilodge.com',
        'Instagram_Page': 'https://instagram.com/tarangiresafarilodge',
        'Facebook_Page': 'https://facebook.com/tarangiresafarilodge',
        'AI_Visibility_Gap_Signal': 'AI Overviews cite safari directory aggregators; direct booking rates unindexed by Perplexity.',
        'Estimated_Monthly_Bleed_USD': '3900',
        'Tailored_Pitch_Hook': 'Tarangire Safari Lodge has iconic river views, but travelers researching Tarangire on AI engines are pushed to OTAs taking $3,900/mo.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Iconic park lodge with high direct booking potential.'
    },
    {
        'Business_Name': 'Neptune Ngorongoro Luxury Lodge',
        'Country_Region': 'Tanzania (Ngorongoro Conservation Area)',
        'Category': 'All-Inclusive Luxury Safari Lodge',
        'Contact_Person_Or_Title': 'Reservations Manager / Director',
        'Primary_Outreach_Email': 'res.ngorongoro@neptunehotels.com',
        'Secondary_Email': 'info.ngorongoro@neptunehotels.com',
        'WhatsApp_Number': '+255752305709',
        'Phone_Number': '+255752305709',
        'Website_URL': 'https://neptunehotels.com',
        'Instagram_Page': 'https://instagram.com/neptunengorongoro',
        'Facebook_Page': 'https://facebook.com/neptunehotels',
        'AI_Visibility_Gap_Signal': 'High-ticket crater luxury queries in ChatGPT cite OTA portals; direct suite rates bypassed.',
        'Estimated_Monthly_Bleed_USD': '5800',
        'Tailored_Pitch_Hook': 'Neptune Ngorongoro is losing high-ticket direct bookings to Booking.com on premium suites because AI search lacks your live direct schema.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Ultra-luxury lodge. Very high monthly bleed figure.'
    },
    {
        'Business_Name': 'Nyota Boutique Hotel',
        'Country_Region': 'Tanzania (Nungwi, Zanzibar)',
        'Category': 'Boutique Beach Resort & Spa',
        'Contact_Person_Or_Title': 'Owner / General Manager',
        'Primary_Outreach_Email': 'info@nyotazanzibar.com',
        'Secondary_Email': 'reservations@nyotazanzibar.com',
        'WhatsApp_Number': '+255713102127',
        'Phone_Number': '+255713102127',
        'Website_URL': 'https://nyotazanzibar.com',
        'Instagram_Page': 'https://instagram.com/nyotaboutiquehotel',
        'Facebook_Page': 'https://facebook.com/nyotaboutiquehotel',
        'AI_Visibility_Gap_Signal': 'Google Local 3-Pack rank #8 in Zanzibar boutique category; ChatGPT cites TripAdvisor lists.',
        'Estimated_Monthly_Bleed_USD': '2900',
        'Tailored_Pitch_Hook': 'Nyota has incredible oceanfront reviews, but European honeymooners planning via AI are guided to Booking.com instead of your direct engine.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Fast WhatsApp responses in Nungwi.'
    },
    {
        'Business_Name': 'Sharazad Boutique Hotel',
        'Country_Region': 'Tanzania (Jambiani, Zanzibar)',
        'Category': 'Luxury Eco Boutique Hotel & Villas',
        'Contact_Person_Or_Title': 'Managing Director / Host',
        'Primary_Outreach_Email': 'reservations@sharazadboutiquehotel.com',
        'Secondary_Email': 'info@sharazadboutiquehotel.com',
        'WhatsApp_Number': '+255779624061',
        'Phone_Number': '+255779624061',
        'Website_URL': 'https://sharazadboutiquehotel.com',
        'Instagram_Page': 'https://instagram.com/sharazadboutiquehotel',
        'Facebook_Page': 'https://facebook.com/sharazadboutiquehotel',
        'AI_Visibility_Gap_Signal': 'High OTA dependency; lacking AI bot schema allowlist. Leaking thousands monthly to OTAs on Jambiani bookings.',
        'Estimated_Monthly_Bleed_USD': '4800',
        'Tailored_Pitch_Hook': 'Sharazad is paying thousands monthly to OTAs on Jambiani bookings that should originate directly from search and AI travel prompts.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Top eco-boutique property on the island.'
    },
    {
        'Business_Name': 'Kendwa Rocks Beach Hotel',
        'Country_Region': 'Tanzania (Kendwa, Zanzibar)',
        'Category': 'Beachfront Resort & Event Hotel',
        'Contact_Person_Or_Title': 'Bookings Director / General Manager',
        'Primary_Outreach_Email': 'booking@kendwarocks.com',
        'Secondary_Email': 'info@kendwarocks.com',
        'WhatsApp_Number': '+255777415528',
        'Phone_Number': '+255774415475',
        'Website_URL': 'https://kendwarocks.com',
        'Instagram_Page': 'https://instagram.com/kendwarocks',
        'Facebook_Page': 'https://facebook.com/kendwarocksbeachhotel',
        'AI_Visibility_Gap_Signal': 'ChatGPT cites third-party nightlife and hotel booking portals; direct room packages omitted.',
        'Estimated_Monthly_Bleed_USD': '5100',
        'Tailored_Pitch_Hook': 'Kendwa Rocks has high brand awareness, but international travelers searching on AI are routed to Agoda & Booking.com taking 20%.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'High volume beachfront property.'
    },
    {
        'Business_Name': 'B4 Beach Club & Boutique Hotel',
        'Country_Region': 'Tanzania (Paje, Zanzibar)',
        'Category': 'Boutique Hotel & Beachfront Lounge',
        'Contact_Person_Or_Title': 'General Manager / Host',
        'Primary_Outreach_Email': 'contact@b4beach.club',
        'Secondary_Email': 'reservations@b4beach.club',
        'WhatsApp_Number': '+255778672715',
        'Phone_Number': '+255778672715',
        'Website_URL': 'https://b4beach.club',
        'Instagram_Page': 'https://instagram.com/b4beachclub',
        'Facebook_Page': 'https://facebook.com/b4beachclub',
        'AI_Visibility_Gap_Signal': 'Missing schema markup for boutique lodging; Perplexity categorizes only as a club rather than hotel stay.',
        'Estimated_Monthly_Bleed_USD': '3200',
        'Tailored_Pitch_Hook': 'B4 Beach Club is missing lodging entity schema, causing AI search engines to overlook your rooms and route guests to nearby OTA listings.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Paje kitesurfing and boutique hub.'
    },
    {
        'Business_Name': 'Top Guides Bushcamps',
        'Country_Region': 'Tanzania (Arusha / Serengeti)',
        'Category': 'Bespoke Safari Bushcamps & Guided Tours',
        'Contact_Person_Or_Title': 'Director of Operations',
        'Primary_Outreach_Email': 'Info@tbcamps.com',
        'Secondary_Email': 'reservations@tbcamps.com',
        'WhatsApp_Number': '+255684705357',
        'Phone_Number': '+255682111121',
        'Website_URL': 'https://topguidesbushcamps.com',
        'Instagram_Page': 'https://instagram.com/topguidesbushcamps',
        'Facebook_Page': 'https://facebook.com/topguidesbushcamps',
        'AI_Visibility_Gap_Signal': 'Perplexity search for bespoke Tanzania private safari guides returns zero citation for tbcamps.com.',
        'Estimated_Monthly_Bleed_USD': '3100',
        'Tailored_Pitch_Hook': 'Top Guides Bushcamps has premier safari guides, but private itinerary queries in AI search are being captured by UK/US broker sites.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Expert guiding safari company.'
    },

    # --- KENYA ---
    {
        'Business_Name': 'Mara Nyika Camp (The Boutique Safari)',
        'Country_Region': 'Kenya (Naboisho / Maasai Mara)',
        'Category': 'Luxury Boutique Safari Camp',
        'Contact_Person_Or_Title': 'General Manager / Camp Host',
        'Primary_Outreach_Email': 'bookings@theboutiquesafari.com',
        'Secondary_Email': 'info@theboutiquesafari.com',
        'WhatsApp_Number': '+254713245622',
        'Phone_Number': '+254713245622',
        'Website_URL': 'https://theboutiquesafari.com',
        'Instagram_Page': 'https://instagram.com/theboutiquesafari',
        'Facebook_Page': 'https://facebook.com/theboutiquesafari',
        'AI_Visibility_Gap_Signal': 'ChatGPT cites SafariBookings & aggregator blogs; direct booking engine missing from AI results for Naboisho conservancy.',
        'Estimated_Monthly_Bleed_USD': '5400',
        'Tailored_Pitch_Hook': 'Mara Nyika Camp offers premier Maasai Mara luxury, but high-intent international guests searching on ChatGPT are sent to intermediary agents taking 20%.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Premier conservancy property.'
    },
    {
        'Business_Name': 'Lorian Safari Camp',
        'Country_Region': 'Kenya (Maasai Mara)',
        'Category': 'Boutique Tented Safari Camp',
        'Contact_Person_Or_Title': 'General Manager / Reservations',
        'Primary_Outreach_Email': 'info@loriansafaricamp.com',
        'Secondary_Email': 'reservations@loriansafaricamp.com',
        'WhatsApp_Number': '+254768930718',
        'Phone_Number': '+254768930718',
        'Website_URL': 'https://loriansafaricamp.com',
        'Instagram_Page': 'https://instagram.com/loriansafaricamp',
        'Facebook_Page': 'https://facebook.com/loriansafaricamp',
        'AI_Visibility_Gap_Signal': 'GBP missing secondary categories (Tour Operator, Safari Park); missing FAQ schema for AI indexing.',
        'Estimated_Monthly_Bleed_USD': '2800',
        'Tailored_Pitch_Hook': 'Lorian Safari Camp is missing 3 key GBP secondary categories that would place you in the top 3 Google local pack for Mara visitors.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Authentic tented camp.'
    },
    {
        'Business_Name': 'Almanara Luxury Resort',
        'Country_Region': 'Kenya (Diani Beach)',
        'Category': 'Luxury Boutique Villas & Beach Resort',
        'Contact_Person_Or_Title': 'Managing Director / GM',
        'Primary_Outreach_Email': 'info@almanararesort.com',
        'Secondary_Email': 'reservations@almanararesort.com',
        'WhatsApp_Number': '+254711852026',
        'Phone_Number': '+254711852026',
        'Website_URL': 'https://almanararesort.com',
        'Instagram_Page': 'https://instagram.com/almanararesort',
        'Facebook_Page': 'https://facebook.com/almanararesort',
        'AI_Visibility_Gap_Signal': 'ChatGPT routes private luxury villa queries on Diani Beach to Expedia; Almanara direct domain uncited.',
        'Estimated_Monthly_Bleed_USD': '4900',
        'Tailored_Pitch_Hook': 'Almanara has Diani Beach’s most exclusive villas, but AI search engines are directing high-net-worth travelers to OTAs charging 18%.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Top-tier luxury villas in Kenya.'
    },
    {
        'Business_Name': 'Asha Boutique Hotel & Bistro',
        'Country_Region': 'Kenya (Diani Beach)',
        'Category': 'Boutique Beachfront Hotel',
        'Contact_Person_Or_Title': 'General Manager / Host',
        'Primary_Outreach_Email': 'reservations@ashaboutiquehotel.com',
        'Secondary_Email': 'info@ashaboutiquehotel.com',
        'WhatsApp_Number': '+254115065158',
        'Phone_Number': '+254115065158',
        'Website_URL': 'https://ashaboutiquehotel.com',
        'Instagram_Page': 'https://instagram.com/ashaboutiquehotel',
        'Facebook_Page': 'https://facebook.com/ashaboutiquehotel',
        'AI_Visibility_Gap_Signal': 'Lacks LodgingBusiness JSON-LD markup; missing from Google AI Overviews for intimate Diani boutique stays.',
        'Estimated_Monthly_Bleed_USD': '2600',
        'Tailored_Pitch_Hook': 'Asha Boutique Hotel is leaking an estimated $2,600/mo to Booking.com on Diani stays because search bots cannot parse your room availability.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Charming boutique hotel on Diani Beach.'
    },
    {
        'Business_Name': 'Natural World Kenya Safaris',
        'Country_Region': 'Kenya (Nairobi & Diani Beach)',
        'Category': 'Premier Kenya Safari Tour Operator',
        'Contact_Person_Or_Title': 'Director of Safari Operations',
        'Primary_Outreach_Email': 'dianisafari@naturaltoursandsafaris.com',
        'Secondary_Email': 'info@naturaltoursandsafaris.com',
        'WhatsApp_Number': '+254758499503',
        'Phone_Number': '+254758499503',
        'Website_URL': 'https://naturaltoursandsafaris.com',
        'Instagram_Page': 'https://instagram.com/naturalworldkenyasafaris',
        'Facebook_Page': 'https://facebook.com/naturalworldkenyasafaris',
        'AI_Visibility_Gap_Signal': 'High SEO authority on traditional Google, but Perplexity cites international aggregators for customized Kenya safari itineraries.',
        'Estimated_Monthly_Bleed_USD': '4500',
        'Tailored_Pitch_Hook': 'Natural World has exceptional Google rankings, but the new wave of AI trip planners on ChatGPT and Perplexity are giving safari leads to broker sites.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'High volume tour operator ready for GEO upgrade.'
    },
    {
        'Business_Name': 'Mtito Safari Camp',
        'Country_Region': 'Kenya (Tsavo / Maasai Mara)',
        'Category': 'Mid-to-High Safari Lodge & Camp',
        'Contact_Person_Or_Title': 'Managing Director',
        'Primary_Outreach_Email': 'bookings@mtitosafaricamp.com',
        'Secondary_Email': 'info@mtitosafaricamp.com',
        'WhatsApp_Number': '+254758724813',
        'Phone_Number': '+254794668951',
        'Website_URL': 'https://mtitosafaricamp.com',
        'Instagram_Page': 'https://instagram.com/mtitosafaricamp',
        'Facebook_Page': 'https://facebook.com/mtitosafaricamp',
        'AI_Visibility_Gap_Signal': 'Low direct booking search ranking; Google AI Overviews cite third-party travel blogs.',
        'Estimated_Monthly_Bleed_USD': '2500',
        'Tailored_Pitch_Hook': 'Mtito Safari Camp is handing an estimated $2,500/mo to OTA platforms on Tsavo and Mara safari reservations.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM EAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM EAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'High potential for direct booking lift.'
    },

    # --- NAMIBIA ---
    {
        'Business_Name': 'Casa Blanca Boutique Hotel',
        'Country_Region': 'Namibia (Windhoek)',
        'Category': 'Boutique Hotel & Executive Lodge',
        'Contact_Person_Or_Title': 'General Manager / Owner',
        'Primary_Outreach_Email': 'reservations@casablancahotel.com.na',
        'Secondary_Email': 'info@casablancahotel.com.na',
        'WhatsApp_Number': '+264816435126',
        'Phone_Number': '+26461249623',
        'Website_URL': 'https://casablancahotel.com.na',
        'Instagram_Page': 'https://instagram.com/casablancaboutiquehotel',
        'Facebook_Page': 'https://facebook.com/casablancahotelwindhoek',
        'AI_Visibility_Gap_Signal': 'Perplexity query for best boutique stays in Windhoek yields zero direct citations for Casa Blanca.',
        'Estimated_Monthly_Bleed_USD': '2700',
        'Tailored_Pitch_Hook': 'Executive and self-drive tourists in Windhoek booking via AI are sent straight to Booking.com, taking 15% off every Casa Blanca room night.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Pristine Windhoek boutique property.'
    },
    {
        'Business_Name': 'Atlantic Villa Boutique Guesthouse',
        'Country_Region': 'Namibia (Swakopmund)',
        'Category': 'Coastal Boutique Guesthouse & Villas',
        'Contact_Person_Or_Title': 'Managing Director',
        'Primary_Outreach_Email': 'bookings@atlantic-villa.com',
        'Secondary_Email': 'events@atlantic-villa.com',
        'WhatsApp_Number': '+26464463511',
        'Phone_Number': '+26464463511',
        'Website_URL': 'https://atlantic-villa.com',
        'Instagram_Page': 'https://instagram.com/atlanticvillaboutique',
        'Facebook_Page': 'https://facebook.com/atlanticvillaboutiqueguesthouse',
        'AI_Visibility_Gap_Signal': 'Lacks LodgingBusiness schema; Google 3-pack dropped behind older Swakopmund chain hotels.',
        'Estimated_Monthly_Bleed_USD': '3400',
        'Tailored_Pitch_Hook': 'Atlantic Villa has prime Swakopmund ocean views, but is leaking over $3,000 monthly to OTAs due to unoptimized AI crawler access.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Top coastal destination in Namibia.'
    },
    {
        'Business_Name': 'Beach Lodge Swakopmund',
        'Country_Region': 'Namibia (Swakopmund)',
        'Category': 'Oceanfront Boutique Lodge',
        'Contact_Person_Or_Title': 'General Manager / Host',
        'Primary_Outreach_Email': 'reservations@beachlodge.com.na',
        'Secondary_Email': 'info@beachlodge.com.na',
        'WhatsApp_Number': '+264811273397',
        'Phone_Number': '+26464414500',
        'Website_URL': 'https://beachlodge.com.na',
        'Instagram_Page': 'https://instagram.com/beachlodgeswakopmund',
        'Facebook_Page': 'https://facebook.com/beachlodgeswakop',
        'AI_Visibility_Gap_Signal': 'ChatGPT fails to cite Beach Lodge for Swakopmund direct beachfront stays; cites aggregators instead.',
        'Estimated_Monthly_Bleed_USD': '2900',
        'Tailored_Pitch_Hook': 'Beach Lodge is directly on the water, but travelers asking AI where to stay in Swakopmund are never shown your direct booking rate.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Prime beachfront property.'
    },
    {
        'Business_Name': 'Namibia Destinations',
        'Country_Region': 'Namibia (Windhoek)',
        'Category': 'Bespoke Safari & Self-Drive Tour Operator',
        'Contact_Person_Or_Title': 'Managing Director / Tour Manager',
        'Primary_Outreach_Email': 'reservations@namibiadestinations.com',
        'Secondary_Email': 'info@namibiadestinations.com',
        'WhatsApp_Number': '+264817367654',
        'Phone_Number': '+264817367654',
        'Website_URL': 'https://namibiadestinations.com',
        'Instagram_Page': 'https://instagram.com/namibiadestinations',
        'Facebook_Page': 'https://facebook.com/namibiadestinations',
        'AI_Visibility_Gap_Signal': 'Perplexity queries for guided Namibia 4x4 self-drive tours recommend international OTA portals rather than local operators.',
        'Estimated_Monthly_Bleed_USD': '3300',
        'Tailored_Pitch_Hook': 'Self-drive travelers researching Namibia safari routes via AI are booking through overseas agencies instead of reaching Namibia Destinations direct.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Key self-drive & safari operator in Windhoek.'
    },
    {
        'Business_Name': 'Mannor Safaris Namibia',
        'Country_Region': 'Namibia (Windhoek)',
        'Category': 'Custom Safari & Wildlife Tour Agency',
        'Contact_Person_Or_Title': 'Founder / Lead Guide',
        'Primary_Outreach_Email': 'info@mannorsafaris.com',
        'Secondary_Email': 'bookings@mannorsafaris.com',
        'WhatsApp_Number': '+264818577667',
        'Phone_Number': '+264818577667',
        'Website_URL': 'https://mannorsafaris.com',
        'Instagram_Page': 'https://instagram.com/mannorsafaris',
        'Facebook_Page': 'https://facebook.com/mannorsafaris',
        'AI_Visibility_Gap_Signal': 'Missing structured entity markup for wildlife itineraries; absent from ChatGPT top recommendations.',
        'Estimated_Monthly_Bleed_USD': '2800',
        'Tailored_Pitch_Hook': 'Mannor Safaris has expert wildlife knowledge, but AI search engines cannot read your itineraries without GEO structured data.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Growing safari operator.'
    },

    # --- RWANDA ---
    {
        'Business_Name': 'Inganzo Boutique Hotel',
        'Country_Region': 'Rwanda (Kigali)',
        'Category': 'Boutique Hotel & Executive Suites',
        'Contact_Person_Or_Title': 'General Manager / Owner',
        'Primary_Outreach_Email': 'reservations@inganzohotel.com',
        'Secondary_Email': 'info@inganzohotel.com',
        'WhatsApp_Number': '+250788300000',
        'Phone_Number': '+250788300000',
        'Website_URL': 'https://inganzohotel.com',
        'Instagram_Page': 'https://instagram.com/inganzohotel',
        'Facebook_Page': 'https://facebook.com/inganzoboutiquehotel',
        'AI_Visibility_Gap_Signal': 'AI search assistants (ChatGPT/Perplexity) route Kigali business travelers to Expedia and Booking.com.',
        'Estimated_Monthly_Bleed_USD': '2400',
        'Tailored_Pitch_Hook': 'Diplomatic and business travelers planning stays in Kigali via AI assistants are bypassing Inganzo Hotel direct rates.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Kigali boutique hotel.'
    },
    {
        'Business_Name': 'The Court Boutique Hotel',
        'Country_Region': 'Rwanda (Kigali)',
        'Category': 'Boutique Hotel & Dining',
        'Contact_Person_Or_Title': 'Operations Manager / Director',
        'Primary_Outreach_Email': 'reservations@thecourtboutique.com',
        'Secondary_Email': 'info@thecourtboutique.com',
        'WhatsApp_Number': '+250788123456',
        'Phone_Number': '+250788123456',
        'Website_URL': 'https://thecourtboutique.com',
        'Instagram_Page': 'https://instagram.com/thecourtboutiquehotel',
        'Facebook_Page': 'https://facebook.com/thecourtboutique',
        'AI_Visibility_Gap_Signal': 'GBP missing secondary category tags and entity schema; invisible to ChatGPT prompt for Kigali luxury stays.',
        'Estimated_Monthly_Bleed_USD': '2100',
        'Tailored_Pitch_Hook': 'The Court Boutique Hotel is losing direct corporate reservations to OTAs because Google and AI crawlers cannot index your amenities.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'High-end Kigali dining and lodging.'
    },
    {
        'Business_Name': 'Volcanoes Safaris (Virunga Lodge)',
        'Country_Region': 'Rwanda (Volcanoes National Park)',
        'Category': 'Premier Gorilla Trekking Lodge',
        'Contact_Person_Or_Title': 'General Manager / Enquiries',
        'Primary_Outreach_Email': 'enquiries@volcanoessafaris.com',
        'Secondary_Email': 'sales@volcanoessafaris.com',
        'WhatsApp_Number': '+250788310000',
        'Phone_Number': '+250788310000',
        'Website_URL': 'https://volcanoessafaris.com',
        'Instagram_Page': 'https://instagram.com/volcanoessafaris',
        'Facebook_Page': 'https://facebook.com/volcanoessafaris',
        'AI_Visibility_Gap_Signal': 'High-ticket gorilla trekking searches on AI return third-party overseas booking agencies taking huge agency cuts.',
        'Estimated_Monthly_Bleed_USD': '6500',
        'Tailored_Pitch_Hook': 'Travelers booking $1,500/night gorilla trekking experiences via AI concierge tools are being captured by UK/US intermediaries instead of booking direct.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Flagship ultra-luxury gorilla lodge.'
    },
    {
        'Business_Name': 'Rwanda Safaris (Primate Experiences)',
        'Country_Region': 'Rwanda (Kigali)',
        'Category': 'Gorilla & Primate Safari Tour Operator',
        'Contact_Person_Or_Title': 'Managing Director / Tour Planner',
        'Primary_Outreach_Email': 'info@rwandasafaris.com',
        'Secondary_Email': 'reservations@rwandasafaris.com',
        'WhatsApp_Number': '+250739259965',
        'Phone_Number': '+250739259965',
        'Website_URL': 'https://rwandasafaris.com',
        'Instagram_Page': 'https://instagram.com/rwandasafaris',
        'Facebook_Page': 'https://facebook.com/rwandasafaristours',
        'AI_Visibility_Gap_Signal': 'Perplexity returns third-party aggregator directories for Volcanoes gorilla permits; direct local operator omitted.',
        'Estimated_Monthly_Bleed_USD': '4100',
        'Tailored_Pitch_Hook': 'Rwanda Safaris is losing gorilla permit package bookings to overseas travel brokers because your itineraries lack AI entity schemas.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Top primate tour agency in Kigali.'
    },
    {
        'Business_Name': 'Albertine Tours',
        'Country_Region': 'Rwanda (Kigali)',
        'Category': 'Eco-Tourism & Gorilla Trekking Agency',
        'Contact_Person_Or_Title': 'Director of Tourism',
        'Primary_Outreach_Email': 'info@albertinetours.com',
        'Secondary_Email': 'bookings@albertinetours.com',
        'WhatsApp_Number': '+250788591728',
        'Phone_Number': '+250788591728',
        'Website_URL': 'https://albertinetours.com',
        'Instagram_Page': 'https://instagram.com/albertinetours',
        'Facebook_Page': 'https://facebook.com/albertinetours',
        'AI_Visibility_Gap_Signal': 'Missing Google 3-pack optimization for Kigali tour agencies; absent in ChatGPT prompt responses.',
        'Estimated_Monthly_Bleed_USD': '2900',
        'Tailored_Pitch_Hook': 'Albertine Tours has authentic eco-itineraries, but travelers asking AI for custom Rwanda tours are handed off to European aggregators.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM CAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM CAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Established eco tour operator.'
    },

    # --- CAMEROON ---
    {
        'Business_Name': 'K Hotel Douala',
        'Country_Region': 'Cameroon (Douala Bonanjo)',
        'Category': 'Luxury Business & Boutique Hotel',
        'Contact_Person_Or_Title': 'Directeur Général / Reservations',
        'Primary_Outreach_Email': 'reservations@khoteldouala.com',
        'Secondary_Email': 'info@khoteldouala.com',
        'WhatsApp_Number': '+237655402758',
        'Phone_Number': '+237233507400',
        'Website_URL': 'https://khoteldouala.com',
        'Instagram_Page': 'https://instagram.com/khoteldouala',
        'Facebook_Page': 'https://facebook.com/khoteldouala',
        'AI_Visibility_Gap_Signal': 'ChatGPT query for premier hotels in Douala Bonanjo cites Booking.com aggregators; K Hotel direct booking engine absent.',
        'Estimated_Monthly_Bleed_USD': '3800',
        'Tailored_Pitch_Hook': 'K Hotel is Doualas premier design hotel, but international business travelers planning via AI are guided to Booking.com taking 18% on every room.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM WAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM WAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Premier Douala business hotel. High value client.'
    },
    {
        'Business_Name': 'Star Land Hotel',
        'Country_Region': 'Cameroon (Douala & Yaounde)',
        'Category': 'Boutique Business Hotel & Suites',
        'Contact_Person_Or_Title': 'Direction Commerciale / Marketing',
        'Primary_Outreach_Email': 'info@starlandhotel.com',
        'Secondary_Email': 'reservations@starlandhotel.com',
        'WhatsApp_Number': '+237653074949',
        'Phone_Number': '+237233421100',
        'Website_URL': 'https://starlandhotel.com',
        'Instagram_Page': 'https://instagram.com/starlandhotel',
        'Facebook_Page': 'https://facebook.com/starlandhotel',
        'AI_Visibility_Gap_Signal': 'Lacks JSON-LD schema across both Bonapriso and Bastos properties; absent from AI Overviews.',
        'Estimated_Monthly_Bleed_USD': '3500',
        'Tailored_Pitch_Hook': 'Star Land Hotel is leaking thousands monthly to international OTAs across your Douala and Yaoundé properties due to missing AI search schema.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM WAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM WAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Multi-city Cameroon boutique operator.'
    },
    {
        'Business_Name': 'Hôtel Océan Kribi',
        'Country_Region': 'Cameroon (Kribi)',
        'Category': 'Seaside Resort & Eco Lodge',
        'Contact_Person_Or_Title': 'Directeur d Exploitation',
        'Primary_Outreach_Email': 'reservation@hoteloceankribi.com',
        'Secondary_Email': 'contact@hoteloceankribi.com',
        'WhatsApp_Number': '+237695364392',
        'Phone_Number': '+237670471563',
        'Website_URL': 'https://hoteloceankribi.com',
        'Instagram_Page': 'https://instagram.com/hoteloceankribi',
        'Facebook_Page': 'https://facebook.com/hoteloceankribi',
        'AI_Visibility_Gap_Signal': 'Perplexity search for best seaside eco lodges in Kribi returns generic directory sites without direct hotel citation.',
        'Estimated_Monthly_Bleed_USD': '1800',
        'Tailored_Pitch_Hook': 'Tourists seeking seaside resort getaways in Kribi via Google and AI are not seeing Hôtel Océan direct booking rates.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM WAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM WAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Top leisure destination in Cameroon.'
    },
    {
        'Business_Name': 'West Hotel Douala',
        'Country_Region': 'Cameroon (Douala Akwa)',
        'Category': 'Boutique City Hotel',
        'Contact_Person_Or_Title': 'Direction / Réception',
        'Primary_Outreach_Email': 'reservations@westhoteldouala.com',
        'Secondary_Email': 'info@westhoteldouala.com',
        'WhatsApp_Number': '+237694915119',
        'Phone_Number': '+237694915119',
        'Website_URL': 'https://westhoteldouala.com',
        'Instagram_Page': 'https://instagram.com/westhoteldouala',
        'Facebook_Page': 'https://facebook.com/westhoteldouala',
        'AI_Visibility_Gap_Signal': 'Missing GBP secondary categories and room schema; dropped to page 2 on Google organic.',
        'Estimated_Monthly_Bleed_USD': '2200',
        'Tailored_Pitch_Hook': 'West Hotel in Akwa is paying OTAs 18% per reservation on guests searching for central Douala business lodging.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM WAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM WAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Central business hotel in Douala.'
    },
    {
        'Business_Name': 'Global Bush Travel & Tourism',
        'Country_Region': 'Cameroon (Douala & National Parks)',
        'Category': 'Wildlife & Cultural Tour Operator',
        'Contact_Person_Or_Title': 'Directeur des Opérations',
        'Primary_Outreach_Email': 'info@globalbushtroop.com',
        'Secondary_Email': 'contact@globalbushtroop.com',
        'WhatsApp_Number': '+237677246624',
        'Phone_Number': '+237677246624',
        'Website_URL': 'https://globalbushtroop.com',
        'Instagram_Page': 'https://instagram.com/globalbushtours',
        'Facebook_Page': 'https://facebook.com/globalbushtravel',
        'AI_Visibility_Gap_Signal': 'AI search assistants (ChatGPT/Perplexity) recommend European aggregators for Cameroon wildlife tours; local direct site invisible.',
        'Estimated_Monthly_Bleed_USD': '3100',
        'Tailored_Pitch_Hook': 'Global Bush has Cameroon’s top eco-tours, but travelers asking AI to plan Cameroon wildlife trips are sent to foreign intermediaries.',
        'Touch_1_WhatsApp_Status': 'Ready to Send (2:45 PM WAT)',
        'Touch_2_Email_Status': 'Ready to Send (6:30 PM WAT)',
        'Touch_3_Followup_Status': 'Scheduled',
        'Notes': 'Premier tour operator in Cameroon.'
    }
]

output_file = 'c:/Users/hp/Documents/AFRISHIELD/02 Services ai seo/Afrishieldai SEO SALES AND MARKETING/GBP-Lead-Gen-Conversion-Strategy/AFRISHIELD_HOSPITALITY_LEADS_TRACKER.csv'

fieldnames = [
    'Business_Name',
    'Country_Region',
    'Category',
    'Contact_Person_Or_Title',
    'Primary_Outreach_Email',
    'Secondary_Email',
    'WhatsApp_Number',
    'Phone_Number',
    'Website_URL',
    'Instagram_Page',
    'Facebook_Page',
    'AI_Visibility_Gap_Signal',
    'Estimated_Monthly_Bleed_USD',
    'Tailored_Pitch_Hook',
    'Touch_1_WhatsApp_Status',
    'Touch_2_Email_Status',
    'Touch_3_Followup_Status',
    'Notes'
]

with open(output_file, mode='w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for lead in leads:
        writer.writerow(lead)

print(f'Successfully updated {len(leads)} high-priority leads in {output_file}')
